default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  url:  lyric_manager_development
test:
  <<: *default
  url: lyric_manager_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
